// <auto-generated/>
using System.Text.RegularExpressions;
using TaxIntake.Services;

namespace TaxIntake.Pages
{
    public partial class TabPrimary
    {
        private void FormatPrimarySIN()
        {
            iForm.Primary_SIN = ServiceOperation.FormatSIN(iForm.Primary_SIN);
        }

        private void FormatPrimaryDOB()
        {
            iForm.Primary_DOB = ServiceOperation.FormatDOB(iForm.Primary_DOB);
        }

        private void FormatPostalCode()
        {
            iForm.Primary_Postal_Code = ServiceOperation.FormatPostalCode(iForm.Primary_Postal_Code);
        }
    }
}
